### ISSUE TITLE
Transcoding abort

### ISSUE THREAD

**Issue by tramker** [MerlinCooper/iRacingReplayDirector#11] opened 2019-03-07 09:29 UTC
I've tried to create a record from 2h race and it aborts after 53 minues in the transcoding phase with this error:

2019-03-07T04:46:42	INFO: Transcoding highlights to D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.highlights.wmv
2019-03-07T04:46:42	DEBUG: Attempting to open file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4
2019-03-07T04:46:42	DEBUG: Opened file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4.  Duration: 3212,95
2019-03-07T04:46:42	DEBUG: Searching for audio transcoding for sampleRate of 48khz and 2 channels
2019-03-07T04:46:42	DEBUG: Found audio track.  SampleRate: 48, Channels: 2, BitRate: 440kbs
2019-03-07T04:46:42	INFO: Highlight Edits: Total Duration Target: 00:30:00
2019-03-07T04:46:42	INFO: Highlight Edits: First & last laps.  Duration: 00:02:31.6240000. Remaining: 00:27:28.3760000
2019-03-07T04:46:42	INFO: Highlight Edits: Incident.  Duration: 00:05:27.8630000, Factor: 1,8, Ratio: 590,153544539999
2019-03-07T04:46:42	INFO: Highlight Edits: Restart.  Duration: 00:00:00, Factor: 1, Ratio: 0
2019-03-07T04:46:42	INFO: Highlight Edits: Battle.  Duration: 01:37:13.0190000, Factor: 1,4, Ratio: 8166,22598974
2019-03-07T04:46:42	INFO: Extracting Incident from a total set of 27
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 3
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 5
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 6
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 8
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 10
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 11
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 12
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 13
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 14
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 15
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 17
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 21
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 23
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 27
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 28
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 29
2019-03-07T04:46:42	INFO: Scanning for Incidents for position 30
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 21: 00:00:21.3010000 - 00:00:35.2510000, duration: 00:00:13.9500000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 11: 00:01:27.6990000 - 00:01:36.7000000, duration: 00:00:09.0010000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 12: 00:01:48.8810000 - 00:01:57.8990000, duration: 00:00:09.0180000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 3: 00:07:08.4780000 - 00:07:17.4950000, duration: 00:00:09.0170000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 5: 00:07:40.4950000 - 00:07:49.4780000, duration: 00:00:08.9830000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 8: 00:14:23.9550000 - 00:14:32.9540000, duration: 00:00:08.9990000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 10: 00:37:52.2030000 - 00:38:01.2040000, duration: 00:00:09.0010000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 10: 00:39:17.5350000 - 00:39:26.5190000, duration: 00:00:08.9840000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 3: 00:43:33.8160000 - 00:43:42.7990000, duration: 00:00:08.9830000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 6: 00:44:31.6810000 - 00:44:45.7150000, duration: 00:00:14.0340000
2019-03-07T04:46:42	INFO: Highlight edit Incident @ position 12: 00:55:18.8380000 - 00:55:27.8380000, duration: 00:00:09
2019-03-07T04:46:42	INFO: Highlight Edits: Incident.  Target Duration: 00:01:51.0960000, Percentage: 06%, Resolved Duration: 00:01:48.9700000
2019-03-07T04:46:42	INFO: Extracting Restart from a total set of 0
2019-03-07T04:46:42	INFO: Extracting Battle from a total set of 134
2019-03-07T04:46:42	INFO: Scanning for Battles
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 11: 00:00:45.7330000 - 00:01:27.6990000, duration: 00:00:41.9670000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 00:08:30.9440000 - 00:09:15.9180000, duration: 00:00:44.9750000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 30: 00:16:18.1870000 - 00:17:01.6710000, duration: 00:00:43.4840000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 10: 00:19:23.2520000 - 00:19:48.2350000, duration: 00:00:24.9820000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 6: 00:19:48.2350000 - 00:20:38.2510000, duration: 00:00:50.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 23: 00:20:38.2510000 - 00:21:53.2830000, duration: 00:01:15.0320000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 27: 00:24:03.3150000 - 00:24:58.7470000, duration: 00:00:55.4320000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 00:31:35.4590000 - 00:32:32.5080000, duration: 00:00:57.0490000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 21: 00:38:20.6540000 - 00:39:10.7010000, duration: 00:00:50.0470000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 8: 00:39:26.5190000 - 00:40:00.7190000, duration: 00:00:34.2000000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 21: 00:40:00.7190000 - 00:40:25.7000000, duration: 00:00:24.9810000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 17: 00:45:15.7810000 - 00:46:05.7960000, duration: 00:00:50.0150000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2: 00:46:05.8130000 - 00:47:25.8130000, duration: 00:01:20
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 17: 00:47:25.8130000 - 00:48:40.8440000, duration: 00:01:15.0320000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 4: 00:54:10.9890000 - 00:54:35.9890000, duration: 00:00:24.9990000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 01:00:59.5840000 - 01:02:12.2170000, duration: 00:01:12.6320000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 01:09:37.3270000 - 01:10:17.3430000, duration: 00:00:40.0170000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 01:16:47.3130000 - 01:17:49.8370000, duration: 00:01:02.5250000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 8: 01:20:19.9000000 - 01:21:09.9170000, duration: 00:00:50.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 10: 01:24:09.9820000 - 01:24:59.9970000, duration: 00:00:50.0150000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 16: 01:28:45.1110000 - 01:29:10.1270000, duration: 00:00:25.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 5: 01:30:50.1750000 - 01:32:05.2090000, duration: 00:01:15.0340000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 2147483647: 01:43:25.4580000 - 01:44:05.4650000, duration: 00:00:40.0070000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 20: 01:44:05.4650000 - 01:44:30.4990000, duration: 00:00:25.0340000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 23: 01:47:00.5630000 - 01:47:50.5800000, duration: 00:00:50.0170000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 3: 01:47:50.5800000 - 01:48:40.5780000, duration: 00:00:49.9980000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 3: 01:49:05.5940000 - 01:50:20.6110000, duration: 00:01:15.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 8: 01:53:00.6420000 - 01:53:50.6580000, duration: 00:00:50.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 13: 01:53:50.6580000 - 01:54:15.6740000, duration: 00:00:25.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 24: 01:55:35.6890000 - 01:56:25.7050000, duration: 00:00:50.0160000
2019-03-07T04:46:42	INFO: Highlight edit Battle @ position 3: 01:59:30.7540000 - 02:00:20.7680000, duration: 00:00:50.0140000
2019-03-07T04:46:42	INFO: Highlight Edits: Battle.  Target Duration: 00:25:37.2800000, Percentage: 93%, Resolved Duration: 00:25:22.6000000
2019-03-07T04:46:42	INFO: Highlight Edits: Expected duration of highlight video: 00:29:43.1940000
2019-03-07T04:46:42	DEBUG: Not apply edit between FirstLap:21:21,300633 and Incident:21:21,300633
2019-03-07T04:46:42	DEBUG: Not apply edit between Incident:21:35,2507216 and FirstLap:1:35,2507216
2019-03-07T04:46:42	DEBUG: Not apply edit between FirstLap:1:45,7325897 and Battle:11:45,7325897
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:11:87,6991678 and Incident:11:87,6991678
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:11:96,7000994 and Incident:12:108,881486
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:12:117,8994623 and Incident:3:428,4783193
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:3:437,4952927 and Incident:5:460,4954437
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:5:469,4783273 and Battle:2147483647:510,9435713
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:2147483647:555,9181598 and Incident:8:863,9554748
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:8:872,954426 and Battle:30:978,1871841
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:30:1021,6707953 and Battle:10:1163,2522217
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:10:1188,2346428 and Battle:6:1188,2346428
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:6:1238,2506217 and Battle:23:1238,2506217
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:23:1313,2831112 and Battle:27:1443,3148305
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:27:1498,74724 and Battle:2147483647:1895,4587295
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:2147483647:1952,5079078 and Incident:10:2272,2031747
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:10:2281,2041239 and Battle:21:2300,6538066
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:21:2350,7008684 and Incident:10:2357,5350679
2019-03-07T04:46:42	DEBUG: Not apply edit between Incident:10:2366,5189234 and Battle:8:2366,5189234
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:8:2400,7188527 and Battle:21:2400,7188527
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:21:2425,7002927 and Incident:3:2613,8155683
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:3:2622,7985486 and Incident:6:2671,6805116
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:6:2685,7147942 and Battle:17:2715,7807315
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:17:2765,7957371 and Battle:2:2765,8127528
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:2:2845,8126325 and Battle:17:2845,8126325
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:17:2920,8441424 and Battle:4:3250,9893457
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:4:3275,9888121 and Incident:12:3318,838241
2019-03-07T04:46:42	DEBUG: Applying edit between Incident:12:3327,8382006 and Battle:2147483647:3659,5843221
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:2147483647:3732,2168078 and Battle:2147483647:4177,3268763
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:2147483647:4217,3433839 and Battle:2147483647:4607,31286285
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:2147483647:4669,8374209 and Battle:8:4819,9002535
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:8:4869,9166588 and Battle:10:5049,9821202
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:10:5099,9970937 and Battle:16:5325,1110386
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:16:5350,1267937 and Battle:5:5450,1750593
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:5:5525,2085628 and Battle:2147483647:6205,4577664
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:2147483647:6245,4651503 and Battle:20:6245,4651503
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:20:6270,4986783 and Battle:23:6420,5627837
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:23:6470,579789 and Battle:3:6470,579789
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:3:6520,5779045 and Battle:3:6545,5944171
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:3:6620,6108571 and Battle:8:6780,6422043
2019-03-07T04:46:42	DEBUG: Not apply edit between Battle:8:6830,6581826 and Battle:13:6830,6581826
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:13:6855,6736922 and Battle:24:6935,6894319
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:24:6985,7054103 and Battle:3:7170,7537081
2019-03-07T04:46:42	DEBUG: Applying edit between Battle:3:7220,7678341 and LastLap:2147483647:7295,8014566
2019-03-07T04:46:42	INFO: Editing from 00:01:35.7000000 to 00:01:49.8810000. Duration 14,1813866
2019-03-07T04:46:42	INFO: Editing from 00:01:56.8990000 to 00:07:09.4780000. Duration 312,578857
2019-03-07T04:46:42	INFO: Editing from 00:07:16.4950000 to 00:07:41.4950000. Duration 25,000151
2019-03-07T04:46:42	INFO: Editing from 00:07:48.4780000 to 00:08:31.9440000. Duration 43,465244
2019-03-07T04:46:42	INFO: Editing from 00:09:14.9180000 to 00:14:24.9550000. Duration 310,037315
2019-03-07T04:46:42	INFO: Editing from 00:14:31.9540000 to 00:16:19.1870000. Duration 107,2327581
2019-03-07T04:46:42	INFO: Editing from 00:17:00.6710000 to 00:19:24.2520000. Duration 143,5814264
2019-03-07T04:46:42	INFO: Editing from 00:21:52.2830000 to 00:24:04.3150000. Duration 132,0317193
2019-03-07T04:46:42	INFO: Editing from 00:24:57.7470000 to 00:31:36.4590000. Duration 398,7114895
2019-03-07T04:46:42	INFO: Editing from 00:32:31.5080000 to 00:37:53.2030000. Duration 321,6952669
2019-03-07T04:46:42	INFO: Editing from 00:38:00.2040000 to 00:38:21.6540000. Duration 21,4496826999998
2019-03-07T04:46:42	INFO: Editing from 00:40:24.7000000 to 00:43:34.8160000. Duration 190,1152756
2019-03-07T04:46:42	INFO: Editing from 00:43:41.7990000 to 00:44:32.6810000. Duration 50,8819630000003
2019-03-07T04:46:42	INFO: Editing from 00:44:44.7150000 to 00:45:16.7810000. Duration 32,0659373000003
2019-03-07T04:46:42	INFO: Editing from 00:48:39.8440000 to 00:54:11.9890000. Duration 332,1452033
2019-03-07T04:46:42	INFO: Editing from 00:54:34.9890000 to 00:55:19.8380000. Duration 44,8494289
2019-03-07T04:46:42	INFO: Editing from 00:55:26.8380000 to 01:01:00.5840000. Duration 333,7461215
2019-03-07T04:46:42	INFO: Editing from 01:02:11.2170000 to 01:09:38.3270000. Duration 447,1100685
2019-03-07T04:46:42	INFO: Editing from 01:10:16.3430000 to 01:16:48.3130000. Duration 391,96947895
2019-03-07T04:46:42	INFO: Editing from 01:17:48.8370000 to 01:20:20.9000000. Duration 152,062832600001
2019-03-07T04:46:42	INFO: Editing from 01:21:08.9170000 to 01:24:10.9820000. Duration 182,0654614
2019-03-07T04:46:42	INFO: Editing from 01:24:58.9970000 to 01:28:46.1110000. Duration 227,1139449
2019-03-07T04:46:42	INFO: Editing from 01:29:09.1270000 to 01:30:51.1750000. Duration 102,0482656
2019-03-07T04:46:42	INFO: Editing from 01:32:04.2090000 to 01:43:26.4580000. Duration 682,2492036
2019-03-07T04:46:42	INFO: Editing from 01:44:29.4990000 to 01:47:01.5630000. Duration 152,0641054
2019-03-07T04:46:42	INFO: Editing from 01:48:39.5780000 to 01:49:06.5940000. Duration 27,0165126000002
2019-03-07T04:46:42	INFO: Editing from 01:50:19.6110000 to 01:53:01.6420000. Duration 162,0313472
2019-03-07T04:46:42	INFO: Editing from 01:54:14.6740000 to 01:55:36.6890000. Duration 82,0157396999994
2019-03-07T04:46:42	INFO: Editing from 01:56:24.7050000 to 01:59:31.7540000. Duration 187,0482978
2019-03-07T04:46:42	INFO: Editing from 02:00:19.7680000 to 02:01:36.8010000. Duration 77,0336224999992
2019-03-07T04:46:42	INFO: Total Edits time 01:34:45.5980000
2019-03-07T04:46:42	File index: 1, Duration: 3212,95, OffsetV: 3212,95
2019-03-07T04:46:42	ERROR: Error.  Edit starting position beyond end of segment. 7219,7678341, 3212,95, 0
2019-03-07T04:46:42	ERROR:    v MediaFoundation.Net.AVOperations.<>c__DisplayClass21_0.<Cut>b__0(SourceReaderSample sample)
   v MediaFoundation.Net.AVOperations.<>c__DisplayClass22_0.<SeperateAudioVideo>b__0(SourceReaderSample sample)
   v MediaFoundation.Net.AVOperations.<>c__DisplayClass4_1.<Concat>b__1(SourceReaderSample s)
   v MediaFoundation.Net.AVOperations.<>c__DisplayClass0_0.<FromSource>b__0(ProcessSample next)
   v MediaFoundation.Net.AVOperations.<>c__DisplayClass4_0.<Concat>b__0(Int64 offsetA, Int64 offsetV)
   v iRacingReplayOverlay.Phases.TranscodeAndOverlay.<>c__DisplayClass5_0.<Process>b__0(IEnumerable`1 readers, ProcessSample saveToSink)
   v iRacingReplayOverlay.Phases.Transcoding.Transcoder.ProcessVideo(Action`2 process)
   v iRacingReplayOverlay.Phases.TranscodeAndOverlay.Process(Transcoder transcoder, Boolean highlights, Action`2 monitorProgress, Func`1 isAborted)
2019-03-07T04:46:42	ERROR: Error.  Edit starting position beyond end of segment. 7219,7678341, 3212,95, 0
2019-03-07T04:46:42	ERROR:    v iRacingReplayOverlay.Phases.TranscodeAndOverlay.Process(Transcoder transcoder, Boolean highlights, Action`2 monitorProgress, Func`1 isAborted)
   v iRacingReplayOverlay.Phases.TranscodeAndOverlay.Apply(String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, Func`1 isAborted, String pluginName)
2019-03-07T04:46:42	ERROR: Error.  Edit starting position beyond end of segment. 7219,7678341, 3212,95, 0
2019-03-07T04:46:42	ERROR:    v iRacingReplayOverlay.Phases.TranscodeAndOverlay.Apply(String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, Func`1 isAborted, String pluginName)
   v iRacingReplayOverlay.Phases.TranscodeAndOverlayArguments.Apply()
   v iRacingReplayOverlay.Phases.TranscodeAndOverlayArguments.Apply()
   v iRacingReplayOverlay.Phases.TranscodeAndOverlayMarshaled.Apply(String name, String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, CancellationToken token)
2019-03-07T04:46:52	INFO: Transcoding full replay to D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.wmv
2019-03-07T04:46:52	DEBUG: Attempting to open file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4
2019-03-07T04:46:52	DEBUG: Opened file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4.  Duration: 3212,95
2019-03-07T04:46:52	DEBUG: Searching for audio transcoding for sampleRate of 48khz and 2 channels
2019-03-07T04:46:52	DEBUG: Found audio track.  SampleRate: 48, Channels: 2, BitRate: 440kbs
2019-03-07T04:46:52	File index: 1, Duration: 3212,95, OffsetV: 3212,95
2019-03-07T06:29:55	INFO: Done Transcoding full replay to D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.wmv
2019-03-07T06:29:55	ERROR: DoĹˇlo k jednĂ© nebo vĂ­ce chybĂˇm.
2019-03-07T06:29:55	ERROR:    v System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   v System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   v iRacingReplayOverlay.Phases.IRacingReplay._OverlayRaceDataOntoVideo(Action`2 progress, Action completed, Boolean highlightOnly, Boolean bShutdownAfterCompleted, CancellationToken token)
   v iRacingReplayOverlay.Phases.IRacingReplay.<>c__DisplayClass35_0.<OverlayRaceDataOntoVideo>b__0()
   v iRacingReplayOverlay.Phases.IRacingReplay.<>c__DisplayClass42_0.<InTheBackground>b__0()
2019-03-07T06:29:55	INFO: Process aborted
2019-03-07T06:29:55	INFO: Moving logging to file D:\MEDIA\iracing\videos\general.log

**Comment by tramker** [comment] 2019-03-07 09:35
[logs.zip](https://github.com/MerlinCooper/iRacingReplayOverlay.net/files/2940485/logs.zip)

**Comment by tramker** [comment] 2019-03-08 14:32
019-03-07T04:46:42 DEBUG: Opened file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4. Duration: 3212,95

The mp4 is over 2 hours long, but here it thinks it's just 53 minutes, why ?

**Comment by MerlinCooper** [comment] 2019-03-10 10:46
Unfortunatly the only person who can really read the traces at the moment would be vipoo (but he seem's no longer to acitve). 

What I could do is debugging the code but to reproduce the failure (which I never had before) I would need your settings and replay file. Would you mind providing them?

P.S.: Does the failure mode happen every you try to transcode?

You should finde the setting file in the same directory the exe-file is stored. It's called (iRacingReplayOverlay.exe.config)

**Comment by MerlinCooper** [comment] 2019-03-10 10:47
By the way - what version of the iRacingReplay Director are you using?

**Comment by tramker** [comment] 2019-03-10 12:14
Replay here: http://bid.iline.cz/~mk/tmp/majors.7z
I'm using Build 2019-03 and integrated iRacing video capture to mp4, 1280x720, 60fps.
It happens every time, but only with this long replay, I produced 40min video sucessfully.
The source mp4 is cut too, something I initially missed: 

2019-03-07T04:46:42 DEBUG: Opened file D:\MEDIA\iracing\videos\2019-03-06 23-05-49_0_0.mp4. Duration: 3212,95

Should be two hours long. But the replayscript is two hours long. I think that's causing the problem. Thinking about it, maybe it's iRacing problem (some hard limit on video ?). Anyway the ReplayDirector should deal with it.
Where are the settings stored ? I can't find it in the program directory.

Settings: [iracing-replay-director.zip](https://github.com/MerlinCooper/iRacingReplayOverlay.net/files/2950459/iracing-replay-director.zip)

**Comment by MerlinCooper** [comment] 2019-03-10 21:09
Took me a while to figure out where the original application stored the settings. Could you have a look for a document called "iracing-replay-director.settings" in your documents folder (%userprofile%\documents).

Thanks in advance. Already figured out one issue with the progress bar for transcoding - was an issue that a long datatype was used instead of an unsigned long which causes the current position being a negative number when the most significant bit is set.

**Comment by MerlinCooper** [comment] 2020-06-07 10:19
Link to Azure Boards [AB#3](https://dev.azure.com/MerlinCooperDev/95d08889-0263-422c-90ee-87c9b773fec0/_workitems/edit/3)

**Comment by MerlinCooper** [comment] 2023-02-26 21:42
Closing the issue because haven‘t been able to reproduce

**Closed as completed by MerlinCooper** 2023-02-26 21:42 UTC
Labels: bug, Can't reproduce
