### ISSUE TITLE
Index was outside the bounds of the array exception in MediaFoundation.Net

### ISSUE THREAD

**Issue by pugwonk** [MerlinCooper/iRacingReplayDirector#101] opened 2023-03-03 23:17 UTC
I've got a crash when running "Verify Video Capture". I downloaded the source but that didn't help me much as the crash is in MediaFoundation.Net. I did try to get the source for that too but I got terribly confused about the relationship between SuperMFLib and MediaFoundation.Net and couldn't get them to compile.

I am happy to run this in debug if someone can give me a hand with the dependencies!

Stack trace is below:

```
Frame Rate: 60, Frame Size: 2560x1440, Video: H264 @ 52Mbs, Audio: AAC, 48Khz @ 12Kbs, 
Begining video re-encoding.
Index was outside the bounds of the array.
   at MediaFoundation.Net.SourceReader.<Samples>d__4.MoveNext()
   at MediaFoundation.Net.SourceReader.Samples(ProcessSample samplesFn, Int32 streamIndex, Int32 controlFlags)
   at MediaFoundation.Net.SourceReader.Samples(ProcessSample samplesFn)
   at iRacingReplayDirector.TestVideoCapture.<>c.<TranscodeVideoTest>b__10_0(IEnumerable`1 readers, ProcessSample saveToSink)
   at iRacingReplayDirector.Phases.Transcoding.Transcoder.ProcessVideo(Action`2 process)
   at iRacingReplayDirector.TestVideoCapture.TranscodeVideoTest(String filename)
   at iRacingReplayDirector.TestVideoCapture.RunTest(String workingFolder, SynchronizationContext context)

```

**Comment by MerlinCooper** [comment] 2023-03-05 06:21
Could you provide a. Screenshot of the about dialog and the log file generated? The replay file used when running ‚verify video captured´ would be good as well.

the structure / dependencies are indeed complicated. I thin at the time the application was generated some features like video encoding where not supported so well and that‘s why the originator used a combination of class-libraries.

**Comment by pugwonk** [comment] 2023-03-06 07:31
Here you are! The replay file is nearly 1gb so I've put it [here](https://www.dropbox.com/s/f6l3b6w28g39jfc/subses60211292.rpy?dl=0).

![image](https://user-images.githubusercontent.com/224233/223045496-2cd79d6a-7eac-4dd3-95e1-a84ebe920b5a.png)


![image](https://user-images.githubusercontent.com/224233/223045435-17b0141c-13b2-42da-9ec9-a9681e3ccbd2.png)

**Comment by pugwonk** [comment] 2023-03-12 00:57
For what it's worth, I just tried this on another replay file and got the same error.

**Comment by MerlinCooper** [comment] 2023-03-12 21:32
Can't really reproduce the issue - did with the provided replay file two short videos. One using the "Fast-Video-Recording" and the other with "Encode Video After Capture".

Here are the generated mp4 files and replay-scripts:
https://1drv.ms/f/s!Ato3RDRX7tvH4lWwENCwaDessJsE?e=nw1Njc

Would you mind sharing your settings? You can find the files named "iracing-replay-director.settings" and "iracing-application-version-manager.settings" in your documents folder. Or you just try my settings. Added your name to the list of preferred drivers for testing. 

[Settings_in_Documents_folder.zip](https://github.com/MerlinCooper/iRacingReplayDirector/files/10951861/Settings_in_Documents_folder.zip)


Another potential root cause could be the file format/settings you are using in your recording software. Not all formats are supported - that's a limitation during transcoding. These are the settings I am using in OBS. 
![grafik](https://user-images.githubusercontent.com/3088879/224569110-323d7d6b-2798-46cf-a528-b568a3201e1f.png)

**Comment by pugwonk** [comment] 2023-03-12 22:45
Bingo - you hit the nail on the head. I am using the NVidia capture tool, but I had it set to record the mic and system audio into two separate tracks. For anyone else who experiences this error, make sure you have this setting selected in the GeForce options!

![image](https://user-images.githubusercontent.com/224233/224578441-862a0102-5cda-48fb-b45a-783ee688d4c5.png)

**Comment by MerlinCooper** [comment] 2023-03-12 23:30
Closing the issue - was related to settings of recording software

**Closed as completed by MerlinCooper** 2023-03-12 23:30 UTC
Labels: bug
